!
!  cufft_mod.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  6/27/2011 3:48:20 PM
!
! Author:	Adrian D'Alfonso
!			Module to inteface with the CUFFT libraries
!			contains
!					1 2 and 3 dimensional fourier transforms routines

module cufft

integer, public :: CUFFT_FORWARD = -1
integer, public :: CUFFT_INVERSE = 1
integer, public :: CUFFT_R2C = Z'2a' ! Real to Complex (interleaved)
integer, public :: CUFFT_C2R = Z'2c' ! Complex (interleaved) to Real
integer, public :: CUFFT_C2C = Z'29' ! Complex to Complex, interleaved
integer, public :: CUFFT_D2Z = Z'6a' ! Double to Double-Complex
integer, public :: CUFFT_Z2D = Z'6c' ! Double-Complex to Double
integer, public :: CUFFT_Z2Z = Z'69' ! Double-Complex to Double-Complex

interface cufftPlan
	! cufftPlan1d(cufftHandle *plan, int nx,cufftType type,int batch)
	subroutine cufftPlan1d(plan, nx, type) bind(C,name='cufftPlan1d') 
	use iso_c_binding
	integer(c_int):: plan, type
	integer(c_int),value:: nx
	integer(c_int),value:: batch ! = 1
	end subroutine cufftPlan1d
	! cufftPlan2d(cufftHandle *plan, int nx, int ny, cufftType type)
	subroutine cufftPlan2d(plan, nx, ny, type) bind(C,name='cufftPlan2d') 
	use iso_c_binding
	integer(c_int):: plan
	integer(c_int),value:: nx, ny, type
	end subroutine cufftPlan2d
	! cufftPlan2d(cufftHandle *plan, int nx, int ny, cufftType type)
	subroutine cufftPlan3d(plan, nx, ny, nz, type) bind(C,name='cufftPlan3d') 
	use iso_c_binding
	integer(c_int):: plan
	integer(c_int),value:: nx, ny, nz, type
	end subroutine cufftPlan3d
end interface

interface cufftDestroy
	!cufftDestroy(cufftHandle plan)
	subroutine cufftDestroy(plan) bind(C,name='cufftDestroy') 
	use iso_c_binding
	integer(c_int),value:: plan
	end subroutine cufftDestroy
end interface


interface cufftExec
	!single precision version
	!1D execution
	subroutine cufftExecC2C_1d(plan, idata, odata, direction) bind(C,name='cufftExecC2C') 
	use iso_c_binding
	integer(c_int),value:: direction
	integer(c_int),value:: plan
	complex(4),device:: idata(*),odata(*)
	end subroutine cufftExecC2C_1d
	!2D execution
	subroutine cufftExecC2C_2d(plan, idata, odata, direction) bind(c,name='cufftExecC2C') 
	use iso_c_binding
	use m_precision
	integer(c_int),value:: direction
	integer(c_int),value:: plan
	complex(4),device,dimension(:,:) :: idata
	complex(4),device,dimension(:,:) :: odata
	end subroutine cufftExecC2C_2d
	!3D execution
	subroutine cufftExecC2C_3d(plan, idata, odata, direction) bind(c,name='cufftExecC2C') 
	use iso_c_binding
	integer(c_int),value:: direction
	integer(c_int),value:: plan
	complex(4),device,dimension(:,:,:) :: idata
	complex(4),device,dimension(:,:,:) :: odata
	end subroutine cufftExecC2C_3d
	!double precision version
	!1D execution
	subroutine cufftExecZ2Z_1d(plan, idata, odata, direction) bind(C,name='cufftExecZ2Z') 
	use iso_c_binding
	integer(c_int),value:: direction
	integer(c_int),value:: plan
	complex(8),device :: idata(*)
	complex(8),device :: odata(*)
	end subroutine cufftExecZ2Z_1d
	!2D execution
	subroutine cufftExecZ2Z_2d(plan, idata, odata, direction) bind(c,name='cufftExecZ2Z') 
	use iso_c_binding
	use m_precision
	integer(c_int),value:: direction
	integer(c_int),value:: plan
	complex(8),device,dimension(:,:) :: idata
	complex(8),device,dimension(:,:) :: odata
	end subroutine cufftExecZ2Z_2d
	!3D execution
	subroutine cufftExecZ2Z_3d(plan, idata, odata, direction) bind(c,name='cufftExecZ2Z') 
	use iso_c_binding
	integer(c_int),value:: direction
	integer(c_int),value:: plan
	complex(8),device,dimension(:,:,:) :: idata
	complex(8),device,dimension(:,:,:) :: odata
	end subroutine cufftExecZ2Z_3d
end interface



end module cufft

	 